### ISSUE TITLE
Unable To Connect To Devices

### ISSUE THREAD

**Issue by Squibbz** [Hacktivation/iOS-Hacktivation-Toolkit#14]
Have been trying to connect certain devices, including a 7 Plus and 8 Plus, and have yet to be successful in bypassing. Can read the model, firmware, etc. but once I attempt a bypass it gives me the following:

```Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 599, in process_request_thread
	self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
	self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 655, in __init__
	self.handle()
  File "iphonessh/python-client/tcprelay.py", line 82, in handle
	dsock = mux.connect(dev, self.server.rport)
  File "/home/XXXXX/iOS-Hacktivation-Toolkit/iphonessh/python-client/usbmux.py", line 235, in connect
	return connector.connect(device, port)
  File "/home/XXXXX/iOS-Hacktivation-Toolkit/iphonessh/python-client/usbmux.py", line 206, in connect
	raise MuxError("Connect failed: error %d"%ret)
MuxError: Connect failed: error 3
```

If I could get any help it could be very much appreciated! Still very impressed with your program!

**Comment by Hacktivation** [comment]
Did you run the first option to install?
